config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  #localhost:3000/posts
  get 'posts/index', to: 'posts#index'
  get 'posts/new', to: 'posts#new'
  post 'posts/create', to:'posts#create'
  get 'posts/:id/edit', to: 'posts#edit'
  patch 'posts/:id', to: 'posts#update'
  delete 'posts/:id', to: 'posts#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  validate :start_date_before_end_date

  private

  def start_date_before_end_date
    return if start_date.blank? || end_date.blank?

    if start_date > end_date
      errors.add(:start_date)
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
      @posts = Post.all
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(params.require(:post).permit(:title, :start_date, :end_date, :all_day, :memo ))
      if @post.save
        flash[:notice] = "スケジュールを登録しました"
        redirect_to :posts
      
      else
        render "new"
        flash[:notice] = "登録に失敗しました"
      end
    end

    def show
      @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      if @post.update(params.require(:post).permit(:title, :start_date, :end_date, :all_day, :memo))
          flash[:notice] = "スケジュールを更新しました"
          redirect_to :posts
      else
          render:edit
          flash[:notice] ="更新に失敗しました"
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      flash[:notice] = "スケジュールを削除しました"
      redirect_to :posts
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # app/helpers/application_helper.rb
  end
  

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>予定を編集してください</h1>
<%= form_with model: @post do |form| %>
  <div><%= form.label :title ,"タイトル" %> <br> <%= form.text_field :title,required:true,maxlength:20 %></div>
  <div><%= form.label :start_date ,"開始日" %> <br> <%= form.date_field :start_date,required:true %></div>
  <div><%= form.label :end_date ,"終了日" %> <br> <%= form.date_field :end_date,required:true %></div>
  <div><%= form.check_box :all_day %><%= form.label :all_day, "終日の場合はチェックを入れます" %></div>
  <div><%= form.label :memo ,"スケジュールメモ" %> <br> <%= form.text_area :memo,maxlength:500 %></div>
  <div><%= form.submit "保存" %></div> 
  <div><%= link_to "キャンセル", :posts %></div>
<% end %>

app/views/posts/index.html.erb
<h1>予定一覧</h1>
<p><%= link_to "新規追加", :new_post %></p>

<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= post.start_date.strftime("%Y/%m/%d") %></td>
        <td><%= post.end_date.strftime("%Y/%m/%d") %></td>
        <td><%= post.all_day ? "◯" : "" %></td>
        <td><%= post.updated_at.in_time_zone("Tokyo").strftime("%Y/%m/%d %H:%M") %></td>
        <td><%= link_to "詳細", post %></td>
        <td><%= link_to "編集", [:edit,post] %></td>
          <td><%= link_to "削除", post, method: :delete, data: { confirm: "#{post.title}を削除してよろしいですか?この操作は取り消せません。" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>予定の新規追加</h1>
<%= form_with model: @post do |form| %>
  <div><%= form.label :title ,"タイトル" %> <br> <%= form.text_field :title,required:true,maxlength:20 %></div>
  <div><%= form.label :start_date ,"開始日" %> <br> <%= form.date_field :start_date,required:true %></div>
  <div><%= form.label :end_date ,"終了日" %> <br> <%= form.date_field :end_date,required:true %></div>
  <div><% if @post.errors.any? %>
    <p><%= pluralize(@post.errors.count, "終了日は開始日以降の日付で選択してください。") %> </p><% end %>
  </div>
  <div><%= form.check_box :all_day %><%= form.label :all_day, "終日の場合はチェックを入れます" %></div>
  <div><%= form.label :memo ,"スケジュールメモ" %> <br> <%= form.text_area :memo,maxlength:500 %></div>
  <div><%= form.submit "保存" %></div> 
  <div><%= link_to "キャンセル", :posts %></div>
<% end %>

app/views/posts/show.html.erb
<h1>予定詳細</h1>

<div class="yoko"><h3><%= @post.title %></h3><h3 class="hen"><%= link_to '編集', edit_post_path(@post) %></h3></div>

<table>
  <tr>
    <th>開始日</th>
    <td><%= @post.start_date.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @post.end_date.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td><%= @post.all_day ? "◯" : "" %></td>
  </tr>
  <tr>
    <th>メモ</th>
    <td><%= @post.memo %></td>
  </tr>
</table>

<div>
  <ul>
    <li><%= link_to "一覧に戻る", :posts %></li>
  </ul>
</div>